// resources/js/Components/Notifications/SimpleNotification.tsx
import React, {forwardRef} from "react";
import {CheckCircleIcon, XCircleIcon, XMarkIcon} from "@heroicons/react/24/outline";

type SimpleNotificationProps = {
    dismiss(): void,
    type: 'success' | 'error',
    title: string,
    description: string,
}

const SimpleNotification = forwardRef<unknown, SimpleNotificationProps>((props, ref) => {
    return (
        <div ref={ref} className="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
            <div className="p-4">
                <div className="flex items-start">
                    <div className="flex-shrink-0">
                        { props.type === 'success' && (
                            <CheckCircleIcon className="h-6 w-6 text-green-400" aria-hidden="true" />
                        ) }
                        { props.type === 'error' && (
                            <XCircleIcon className="h-6 w-6 text-red-400" aria-hidden="true" />
                        ) }
                    </div>
                    <div className="ml-3 w-0 flex-1 pt-0.5">
                        <p className="text-sm font-medium text-gray-900">{ props.title }</p>
                        <p className="mt-1 text-sm text-gray-500">{ props.description }</p>
                    </div>
                    <div className="ml-4 flex flex-shrink-0">
                        <button
                            type="button"
                            className="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                            onClick={() => props.dismiss()}
                        >
                            <span className="sr-only">Close</span>
                            <XMarkIcon className="h-5 w-5" aria-hidden="true" />
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
});

export default SimpleNotification;

// resources/js/Components/Generic/Notifications/SimpleNotification.vue
<template>
    <div class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
        <div class="p-4">
            <div class="flex items-start">
                <div class="flex-shrink-0">
                    <CheckCircleIcon class="h-6 w-6 text-green-400" aria-hidden="true" />
                </div>
                <div class="ml-3 w-0 flex-1 pt-0.5">
                    <p class="text-sm font-medium text-gray-900">{{ title }}</p>
                    <p class="mt-1 text-sm text-gray-500">{{ message }}</p>
                </div>
                <div class="ml-4 flex flex-shrink-0">
                    <button type="button" @click="emit('close')" class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                        <span class="sr-only">Close</span>
                        <XMarkIcon class="h-5 w-5" aria-hidden="true" />
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>
<script setup>
import {CheckCircleIcon} from "@heroicons/vue/24/outline";
import {XMarkIcon} from "@heroicons/vue/20/solid";

defineProps({
    title: String,
    message: String,
})

const emit = defineEmits({
    close: null,
})
</script>
